# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 22:45
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cafe', '0003_auto_20170228_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverystaff',
            name='actual_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       to='cafe.DeliveryOrder'),
        ),
    ]
