# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cafe', '0004_auto_20170301_0145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryorder',
            options={'verbose_name': 'Заказ на доставку', 'verbose_name_plural': 'Заказы на доставку'},
        ),
        migrations.AlterModelOptions(
            name='deliverystaff',
            options={'verbose_name': 'Служба доставки', 'verbose_name_plural': 'Служба доставки'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Блюдо', 'verbose_name_plural': 'Блюда'},
        ),
        migrations.AlterModelOptions(
            name='reservationorder',
            options={'verbose_name': 'Заявка на бронирование', 'verbose_name_plural': 'Заявки на бронирование'},
        ),
        migrations.AddField(
            model_name='deliverystaff',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
