# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cafe', '0005_auto_20170307_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverystaff',
            name='chat_id',
            field=models.CharField(max_length=32, unique=True, verbose_name='ID Telegram'),
        ),
    ]
