# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0006_auto_20170307_0038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=64, unique=True, verbose_name='Название, латиницей'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Стоимость'),
        ),
    ]
