# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0008_auto_20170321_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='date_ordered',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата заказа'),
            preserve_default=False,
        ),
    ]
