# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0013_auto_20170322_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverystaff',
            name='bad_orders',
            field=models.ManyToManyField(related_name='deliverystaff_order_declined', to='cafe.DeliveryOrder'),
        ),
        migrations.AddField(
            model_name='deliverystaff',
            name='good_orders',
            field=models.ManyToManyField(related_name='deliverystaff_order_ended', to='cafe.DeliveryOrder'),
        ),
    ]
