# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0014_auto_20170322_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverystaff',
            name='good_orders',
        ),
        migrations.AddField(
            model_name='deliverystaff',
            name='orders_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Заказов получено'),
        ),
    ]
