# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0015_auto_20170322_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverystaff',
            name='bad_orders',
        ),
        migrations.AddField(
            model_name='deliverystaff',
            name='orders_decline',
            field=models.PositiveIntegerField(default=0, verbose_name='Заказов отказано'),
        ),
    ]
