# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0016_auto_20170322_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationorder',
            name='declined_by',
            field=models.ManyToManyField(to='cafe.DeliveryStaff'),
        ),
    ]
