# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0017_reservationorder_declined_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationorder',
            name='declined_by',
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='declined_by',
            field=models.ManyToManyField(to='cafe.DeliveryStaff'),
        ),
    ]
